export class PageConstants {
  static readonly MAIN_NAVIGATION_ID: string = 'mainNavigationId'
  // 首页
  static readonly MAIN_PAGE: string = 'demo://MainPage'
  // 页面跳转案例
  static readonly PAGE_A: string = 'demo://PageA'
  static readonly PAGE_B: string = 'demo://PageB'
  static readonly PAGE_C: string = 'demo://PageC'
  static readonly PAGE_D: string = 'demo://PageD'
  // 登录拦截案例
  static readonly INTERCEPTOR_CASES: string = 'demo://InterceptorCases'
  static readonly LOGIN_PAGE: string = 'demo://LoginPage'
  // 拦截器修改参数
  static readonly INTERCEPTOR_UPDATE_PARAM: string = 'demo://InterceptorUpdateParam'
  // 生命周期获取参数并与页面UI关联案例
  static readonly LIFECYCLE_CASES: string = 'demo://LifecycleCases'
  // 两次返回退出页面案例
  static readonly BACK_PRESSED_CASES: string = 'demo://BackPressCases'
  // 两次返回退出页面案例
  static readonly ADD_OBSERVER_CASES: string = 'demo://AddObserverCases'
  // 动画展示案例
  static readonly ANIMATOR_CASES: string = 'demo://AnimatorCases'
  // 动画展示案例 - 一次性动画
  static readonly ANIMATOR_CASES_ONCE_ANIMATOR: string = 'demo://AnimatorCases/OnceAnimator'
  // 动画展示案例 - 交互式转场动画
  static readonly ANIMATOR_CASES_INTERACTIVE_ANIMATOR: string = 'demo://AnimatorCases/InteractiveAnimator'
  // 动画展示案例 - 弹窗动画
  static readonly ANIMATOR_CASES_DIALOG_ANIMATOR: string = 'demo://AnimatorCases/DialogAnimator'
  // 动画展示案例 - NavBar生命周期
  static readonly NAVBAR_LIFECYCLE: string = 'demo://NavbarLifecycle'
  // 动画展示案例 - NavBar生命周期 - 嵌套在NavDestination
  static readonly NAVBAR_LIFECYCLE_IN_NST: string = 'demo://NavbarLifecycleInDst'
  static readonly MAP_CASE = 'demo://MapCase'
  static readonly LIST_CASE = 'demo://ListCase'
}